#!/usr/bin/env python3
# -*- coding:utf-8 -*-

import rclpy
from rclpy.node import Node

from std_msgs.msg import Empty

import readchar


if __name__ == '__main__':
    rclpy.init()

    trigger = rclpy.create_node('cancel_trigger_node')
    cancel_pub = trigger.create_publisher(Empty, 'cancel_trigger', 1)
    trigger.get_logger().info('Start: cancel_navigation_trigger')
    trigger.get_logger().info('Input Any Key to Stop Navigation')

    while True:
        kb = readchar.readkey()
        print('Input: ' + str(kb) + ' (' + str(ord(kb)) + ')')
        if ord(kb) == 3: # Ctrl + C
            trigger.get_logger().info("Finish: cancel_navigation_trigger")
            break
        else:
            cancel_pub.publish(Empty())

    trigger.destroy_node()
    rclpy.shutdown()
