
map_server:
  ros__parameters:
    #yaml_filename: "map_square/map.yaml"
    yaml_filename: "/home/common/ros2_ws/src/bot_navigation/maps/map_square/map.yaml"
    #yaml_filename: "/opt/ros/foxy/share/nav2_bringup/maps/turtlebot3_world.yaml"
